#!/bin/zsh

# Color definitions
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ "$#" -lt 1 ]
  then
    echo -e "${GREEN}Missing argument! Please enter project directory you want to run!\n${NC}"
    else
      if [ "$#" -gt 1 ]
        then
          echo -e "${GREEN}Too many arguments! Please enter project directory you want to run!\n${NC}"

          else

            clear

            cd "$1" || { return 127; }

            echo -e "${GREEN}Creating Virtual Environment\n${NC}"
            python -m venv venv

            echo -e "${GREEN}Activating Virtual Environment\n${NC}"
            source venv/bin/activate

            echo -e "${GREEN}Upgrading PIP\n${NC}"
            python -m pip install --upgrade pip
            echo -e "\n"

            echo -e "${GREEN}Downloading required packages\n${NC}"
            python "../../setup.py" "$1"

            gnome-terminal --tab -- sh -c 'python main.py; zsh'

            echo -e "${GREEN}Removing Virtual Environment\n${NC}"
            rm -rf venv
      fi
fi

