#!/bin/zsh

WORK_DIR=$(pwd)

source "$WORK_DIR/Shell/colors.sh"

MAX_ARGS=4


if [ "$#" -lt 1 ]
  then
    exec "$WORK_DIR/Shell/help.sh"
    else
      if [ "$#" -gt "$MAX_ARGS" ]
        then
          echo -e "${GREEN}Too many arguments! Please enter project directory you want to run!\n${NC}"

          else
            if [ "$1" = "--help" ]
              then
                exec "$WORK_DIR/Shell/help.sh" "$@"
            fi
            clear

            cd "$1" || { return 127; }

            echo -e "${GREEN}Creating Virtual Environment\n${NC}"
            python -m venv venv

            echo -e "${GREEN}Activating Virtual Environment\n${NC}"
            source venv/bin/activate

            echo -e "${GREEN}Upgrading PIP\n${NC}"
            python -m pip install --upgrade pip
            echo -e "\n"

            echo -e "${GREEN}Downloading required packages\n${NC}"
            python "../../setup.py" "$1"

            gnome-terminal --tab -- sh -c "python main.py; $SHELL"

            echo -e "${GREEN}Removing Virtual Environment\n${NC}"
            rm -rf venv
      fi
fi

